sklearn_models:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    max_features: "sqrt"
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1

pytorch_model:
  architecture:
    input_dim: 128  
    hidden_dims: [64, 32] 
    output_dim: 1  
    dropout_rate: 0.2
  
  training:
    batch_size: 32
    epochs: 50
    learning_rate: 0.001
    optimizer: "adam"
    early_stopping_patience: 5
    
  loss:
    function: "bce_with_logits"  