# Base paths
artifacts_root: artifacts

# Data configurations
data_paths:
  raw_data: "data/raw.csv"
  train_data: "artifacts/train.csv"
  test_data: "artifacts/test.csv"

split:
  test_size: 0.2
  random_state: 33

# Model configurations
model:
  type: "regression"
  artifact:
    trained_model_path: "artifacts/model.skops"

# Preprocessing configurations
preprocessing:
  methods:
    sg_smooth:
      enabled: false
      params:
        window_length: 15
        polyorder: 2
        deriv: 0
    snv:
      enabled: true
    standard_scaler:
      enabled: true

  order: [snv, standard_scaler]

  artifact:
    preprocesser_template_path: "artifacts/preprocesser_template.skops"
    fitted_preprocessor_path: "artifacts/preprocesser_fitted.skops"

# MLflow tracking configurations
mlflow:
  active: false
  experiment_name: "my_experiment"
  run_name: "default_run"